include $(TOPDIR)/rules.mk

LUCI_TITLE:=USB Mobile Network Data Setting
LUCI_DEPENDS:=+kmod-usb-net +kmod-usb-serial +kmod-usb-serial-option +usb-modeswitch
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-modem-data
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk
