#!/bin/sh

uci -q batch <<-EOF >/dev/null 2>&1
    set ipv6set.config=ipv6set
    set ipv6set.config.enable='1'
    set ipv6set.config.wan6zone='wan6'
    set ipv6set.config.v6dns='1'
    set ipv6set.config.mode='1'
    commit ipv6set
EOF

exit 0
