#!/bin/sh

uci -q batch <<-EOF >/dev/null 2>&1
	set webdav.config=webdav
	set webdav.config.enable='0'
	set webdav.config.port='8000'
	set webdav.config.username='video'
	set webdav.config.password='123456'
	set webdav.config.scope='/mnt/clouddrive/CloudDrive'
	commit webdav
EOF

exit 0
