include $(TOPDIR)/rules.mk

LUCI_TITLE:=IPv6 Set Tools
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=1.6
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature