include $(TOPDIR)/rules.mk

LUCI_TITLE:=IPv6 Settings
LUCI_DEPENDS:=+ip6tables +odhcp6c +odhcpd
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-ipv6set
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk
